local colours = {
    {"tomato", "Tomato", "#FF6347"},
    {"carnelian", "Carnelian", "#b31B1B"},
    {"rosewood", "Rosewood", "#65000B"},
    {"apricot", "Apricot", "#FBCEB1"},
    {"fuchsia", "Fuchsia", "#CA2C92"},
    {"ferrari", "Ferarri", "#FF2800"},
    {"wine", "Wine", "#722F37"},
    {"raspberry", "Raspberry", "#E30B5D"},
    {"coral", "Coral", "#FF7F50"},
    {"phillipine", "Phillipine", "#F26E01"},
    {"gamboge", "Gamboge", "#E89611"},
    {"orioles", "Orioles", "#FB4F14"},
    {"pumpkin", "Pumpkin", "#F5761A"},
    {"flame", "Flame", "#E34A27"},
    {"ember", "Embed", "#8A3324"},
    {"beer", "Beer", "#F28F1C"},
    {"pastel", "Pastel", "#FFFE71"},
    {"mustard", "Mustard", "#FEDC56"},
    {"selective", "Selective", "#FFBA00"},
    {"beige", "Beige", "#F5F5DC"},
    {"bee", "Bee", "#FCE205"},
    {"honey", "Honey", "#FFB200"},
    {"moccasin", "Mocassin", "#FFE4B5"},
    {"jungle", "Jungle", "#29AB87"},
    {"mantis", "Mantis", "#74C365"},
    {"sap", "Sap", "#507D2A"},
    {"hunter", "Hunter", "#355E3B"},
    {"apple", "Apple", "#8DB600"},
    {"pistachio", "Pistachio", "#93C572"},
    {"olive", "Olive", "#708238"},
    {"emerald", "Emerald", "#50C878"},
    {"turquoise", "Turquoise", "#48D1CC"},
    {"sky", "Sky", "#ADD8E6"},
    {"cobalt", "Cobalt", "#0047AB"},
    {"capri", "Capri", "#00BFFF"},
    {"celeste", "Celeste", "#B2FFFF"},
    {"zero", "Zero", "#1F4AB8"},
    {"power", "Power", "#B0E0E6"},
    {"teal", "Teal", "#008080"},
    {"lavender", "Lavender", "#A689E1"},
    {"twilight", "Twilight", "#81516B"},
    {"byzantium", "Byzantium", "#5D2954"},
    {"magnolia", "Magnolia", "#FAE6FA"},
    {"berry", "Berry", "#8D4E85"},
    {"royal", "Royal", "#ACACE6"},
    {"plum", "Plum", "#5946B2"},
    {"orchid", "Orchid", "#DA70D6"},
    {"thistle", "Thisle", "#D8BFD8"},
    {"white", "White", "#FFFFFF"},
    {"black", "Black", "#000000"},
    {"abbey", "Abbey", "#494F55"},
    {"cat", "Cat", "#666362"},
    {"bean", "Bean", "#3D0C02"},
    {"charcoal", "Charcoal", "#36454F"},
    {"eerie", "Eerie", "#1B1B1B"},
    {"ebony", "Ebony", "#555D50"},
    {"granite", "Granite", "#676767"},
    {"gray", "Gray", "#808080"},
    {"wolf", "Wolf", "#504A4B"},
    {"cloud", "Cloud", "#B6B6B4"},
    {"iridium", "Iridium", "#3D3C3A"},
    {"midnight", "Midnight", "#2B1B17"},
    {"onyx", "Onyx", "#353839"},
    {"space", "Space", "#414A4C"},
    {"taupe", "Taupe", "#483C32"},
}

for i in ipairs(colours) do
    
    minetest.register_node("noah:wooden_ladder_" .. colours[i][1], {
        description = colours[i][2] .. " Wooden Ladder",
        tiles = {"wooden_ladder.png^[colorize:" .. colours[i][3]},
        inventory_image = "wooden_ladder.png^[colorize:" .. colours[i][3],
        paramtype = "light",
        paramtype2 = "wallmounted",
        sunlight_propagates = true,
        walkable = false,
        climable = true,
        is_ground_content = false,
        selection_box = {
            type = "wallmounted",
        },
        groups = {
            choppy = 2,
            oddly_breakable_by_hand = 3,
            flammable = 2,
        },
        legacy_wallmounted = true,
        sounds = default.node_sound_wood_defaults(),
    })

end
